
name:  First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: first action
        run: echo "hello world"
      - name: say goodbye
        run: echo "goodbye!"
